In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]

In [3]:
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [8]:
#To get dimensions of an array
arr.shape

(5,)

In [9]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[9,10,11,12]

arr=np.array([lst1,lst2,lst3])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr.shape

(3, 4)

In [12]:
#To change the dimensions of the array
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr.shape

(3, 4)

# Indexing

In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[0]

array([1, 2, 3, 4])

In [17]:
print(arr[0][0],arr[1][3],arr[2][3])

1 8 12


In [18]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [30]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [31]:
arr[1:2,2:]

array([[7, 8]])

In [33]:
arr=np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr=np.arange(0,10).reshape(2,5)

In [58]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
arr=np.arange(0,10,2)

In [36]:
arr

array([0, 2, 4, 6, 8])

In [37]:
#assigns 50 values to arr from range 1,100
arr=np.linspace(1,100,50)

In [38]:
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

# Copy and Broadcasting

In [40]:
arr=np.arange(1,10)

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5:]=-1

In [43]:
arr

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1])

In [44]:
cpy=arr

In [45]:
cpy[5:]=-10

In [46]:
cpy

array([  1,   2,   3,   4,   5, -10, -10, -10, -10])

In [54]:
#arr has changes as cpy is changed(arr is passed to cpy as reference)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr=np.arange(1,10)

In [49]:
cpy=arr.copy()

In [50]:
cpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
cpy[5:]=-10

In [52]:
cpy

array([  1,   2,   3,   4,   5, -10, -10, -10, -10])

In [53]:
#arr is not changed even cpy has changed
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Conditions

In [59]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
#returns a bool array which
arr<2

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [63]:
#returns the elements which satisfies the condition
arr[arr<2]

array([0, 1])

In [64]:
arr=np.ones(5)

In [65]:
arr

array([1., 1., 1., 1., 1.])

In [67]:
arr=np.ones(5,dtype=int)

In [68]:
arr

array([1, 1, 1, 1, 1])

In [69]:
arr=np.ones(9).reshape(3,3)

In [70]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
#random distribution from (0,1)
np.random.rand(3,3)

array([[0.80786025, 0.1049848 , 0.4926464 ],
       [0.38908223, 0.35675821, 0.01316074],
       [0.05798867, 0.82253436, 0.83424715]])

In [73]:
#returns a sample from standard normal distribution
np.random.randn(3,3)

array([[-1.67592689,  0.72699912, -0.50132315],
       [-1.46432351,  0.35221039,  0.44220383],
       [-1.15272629, -0.20745221,  1.56110715]])

In [76]:
np.random.randint(1,101,10).reshape(2,5)

array([[79, 12, 37, 44, 33],
       [42, 62, 24, 45, 50]])